---
repos:

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-json
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black-jupyter

    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            args: [--count, --show-source, --statistics]

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: [--profile, black, --filter-files]

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.23.3
      hooks:
          - id: check-github-workflows

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.9.0
      hooks:
          - id: pyupgrade
            args: [--py37-plus]

    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.1
      hooks:
          - id: nbstripout
